-- noinspection SqlNoDataSourceInspectionForFile

SET SQL_SAFE_UPDATES = 0;

DELETE FROM TEACHER_IN_COURSE;

DELETE FROM GIVEN_ANSWER;

DELETE FROM SUBMITTED_EXAM;

DELETE FROM QUESTION_IN_EXAM;

DELETE FROM EXAM;

DELETE FROM QUESTION;

DELETE FROM EXAMTYPE;

DELETE FROM COURSE;

DELETE FROM TEACHER;

DELETE FROM SEMESTER;

INSERT INTO SEMESTER VALUES(1, 1, 'TestSemester'); 

INSERT INTO TEACHER VALUES(1, 1, 'LastNameTestTeacher', 'FirstNameTestTeacher');

INSERT INTO COURSE VALUES(1, 1, 1, 1, 'APP');

INSERT INTO EXAMTYPE VALUES(1, 'Examen');

/* INSERT INTO QUESTION */

INSERT INTO EXAM VALUES(1, 1, 1, 'APP Examen', 'name-0', '1970-01-01T00:00:06', '1970-01-01T00:00:06', null, '1.0', null);

SET SQL_SAFE_UPDATES = 1;